name: AWS Cost Analysis

on:
  workflow_dispatch:

jobs:
  analyze-cost:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: './scripts/requirements.txt'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ap-northeast-1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Pythonの中でSlack投稿まで完結してる
    - name: Run cost analysis
      env:
        SLACK_APPLICATION_TOKEN: ${{ secrets.SLACK_APPLICATION_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      run: |
        python cost_analysis.py
